### ISSUE TITLE
any chance of a windows msi or exe file?

### ISSUE THREAD

**Issue by Goldmaster** [jim-easterbrook/Photini#243]
Hi there,

I have noticed that photoni is available for windows, yet when I got to releases there is no exe or msi file only source code.

I have had a look at the info which involves downloading python and other programs to get it to run.

Any chance of a exe or msi file being available for use, please?

**Comment by jim-easterbrook** [comment]
I cannot supply such a file.
1/ It would be huge.
2/ It would need to be different for different versions of Windows.
3/ I don't have any Windows since version 7.
4/ There are many choices for different libraries such as `PyQt` vs `PySide`. Different users have different requirements.
5/ The file(s) would need to be remade when any one of the dependencies gets updated.
6/ It's not the Python way to do things.
