### ISSUE TITLE
Geotagging: enhanced marker

### ISSUE THREAD

**Issue by regexgit** [jim-easterbrook/Photini#253]
I just have one very minor improvement to suggest:

After a birdwatching trip, I geotagged several birds in the same place (multi-select then drag&drop onto the map). Then I noticed a mistake, the last one had been photographed at a different location: I selected my photo, moved the red marker and ... shit, all the other photos were also moved to the new location.

Of course this isn't a bug, it's a feature (no irony intended...): the photos belong to the same location group, so it's normal for them to be moved to the new location. I should have deleted the coordinates of the last one to detach it from the group.

What's more, I was warned: when I click on the marker all the photos in the group are selected in the image selector.

But I don't think that's enough, I often have to make location changes and I'd really appreciate it if the marker had a little extra sign (a ‘+’ sign for example) to remind me that several photos are linked to this marker.

**Comment by jim-easterbrook** [comment]
That should be possible.

What you should have done is to select the image(s) with the wrong location, then drag them from the image selector area to the map.

**Comment by regexgit** [comment]
Easier of course, I'm still lacking experience but I hope to improve :smiley:

**Comment by jim-easterbrook** [comment]
There's often more than one way to do something. Dragging from the image selector is particularly useful when you want to move them to another town / city / country / continent.

**Comment by jim-easterbrook** [comment]
I've been doing some experimenting with adding text to markers (e.g. a number to show how many images share that position). Each map provider is different, but several use an HTML element for the marker. So instead of using a simple `img` element you can use a `div` containing the marker image and some text. CSS is used to position the text over the image. Doing all this moves the marker, so the offsets need adjusting. It's all rather messy and the end result doesn't look very good either.

It also doesn't solve your problem - what you need is an indication that some of the marker's images are selected and some not. I might try a striped grey/red marker to show that.

**Comment by regexgit** [comment]
I didn't realize that the display depended on the card provider. If it's complicated forget it, it's a useful improvement but not essential.

**Comment by regexgit** [comment]
Ok for the striped markers, but I don't understand your example: the marker is associated with a single image, so it should be (normal) solid red, right?

**Comment by jim-easterbrook** [comment]
No, the marker is associated with a single location, which several images might share. If all images at that location are selected it would be all red. If none of the images at that location are selected it would be all grey.

**Comment by jim-easterbrook** [comment]
You wanted to highlight that several photos are linked to one marker. For me that's a normal situation, so I would highlight that several photos are linked to one marker and not all of them are selected. (Which is the case with your bird photos after you'd selected the one photo that didn't belong at that location.)

**Comment by regexgit** [comment]
That's right, I hadn't thought of it that way, but it's just what I needed and it's a more elegant solution.

**Comment by jim-easterbrook** [comment]
I think the striped marker is not visible enough - the stripes hide it like a zebra's stripes hide a zebra. A simple half & half marker might be better.
![Screenshot_20240831_102333](https://github.com/user-attachments/assets/3f1ac306-1d4f-4b63-bae3-f49ab0951589)

**Comment by jim-easterbrook** [comment]
(I ought to consider the effect on people with the common red-green colour blindness as well.)

**Comment by jim-easterbrook** [comment]
I've been experimenting with various marker designs, and considering other ways to help with your problem. Nothing I can think of is satisfactory to me.
* Different coloured markers - too confusing, in my use most markers have 2 or more images "attached".
* Only drag the previously selected images - "click-and-drag" is too similar to "click and then drag", but the two actions would have different effects.
* Make "part selected" markers undraggable - same problem as above.

I hope that the more prominent colouring of selected image thumbnails might alert you when you click on a marker before dragging it.

I'll keep this issue open, rather than marking it "won't fix", but I don't plan to do it for the release I want to so in the next week or two.

**Comment by regexgit** [comment]
I've just come back from a trip and geotagged a lot of photos: I've got used to moving the thumbnails instead of the markers so this problem doesn't bother me any more.

However, I've found another problem: I opened a new [ticket](https://github.com/jim-easterbrook/Photini/issues/282)
