### ISSUE TITLE
Map (Azure) error

### ISSUE THREAD

**Issue by regexgit** [jim-easterbrook/Photini#257]
```
==== version info ====
Photini 2024.8.1
  Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
  python-exiv2 0.17.0, exiv2 0.28.3
  PyQt 6.7.1, Qt 6.7.1
  system locale fr, locales: fr-FR fr-Latn-FR fr
  PyEnchant 3.2.2
  styles: Windows, Fusion
  using style: fusion
==== messages ====
23:33:20: ERROR: photini.photinimap: https://atlas.microsoft.com/sdk/javascript/mapcontrol/3/atlas.min.js line 105: Uncaught Error: {"requestedAttributes":{"alpha":true,"stencil":true,"depth":true,"failIfMajorPerformanceCaveat":false,"preserveDrawingBuffer":false,"antialias":false},"statusMessage":"Could not create a WebGL context, VENDOR = 0xffff, DEVICE = 0xffff, Sandboxed = no, Optimus = no, AMD switchable = no, Reset notification strategy = 0x0000, ErrorMessage = OffscreenContext Creation failed, GpuChannelHost creation failed.","type":"webglcontextcreationerror","message":"Failed to initialize WebGL"}
==== end ====
```

With `photini-configure` I switched to PySide6 and get the same error.

**Comment by regexgit** [comment]
Azure is ok on other PC with PyQt5:
```
Photini 2024.8.1
  Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
  python-exiv2 0.16.1, exiv2 0.27.7
  PyQt 5.15.10, Qt 5.15.2
  system locale fr, locales: fr-FR
  styles: Windows, Fusion
  using style: fusion
```

**Comment by jim-easterbrook** [comment]
Azure requires WebGL and has no alternative.

**Comment by jim-easterbrook** [comment]
Commit b539816 provides more graceful handling of map load failures.

**Comment by regexgit** [comment]
> Azure requires WebGL and has no alternative.

So why does it work with Qt5?

The situation is as follows:
Qt6: Mapbox OK, Azure NOK
Qt5: Mapbox NOK, Azure OK

**Comment by regexgit** [comment]
By the way, I wouldn't like to be in your shoes debugging this WebGL mess ...

**Comment by jim-easterbrook** [comment]
WebGL isn't one thing, it's a large set of functions and capabilities. Mapbox and Azure may well require (or test for) different things. Qt5 and Qt6 probably have different versions of chrome (the browser used in WebEngine), which probably report different capabilities.

I don't intend to debug WebGL failures. A computer either has a graphics card and drivers that a map can use or it doesn't. Each map has a test for WebGL compatibility which I can use to show a failure message instead of trying to load the map.

There are several online tests of browser WebGL capability. From the simple https://get.webgl.org/ to the complex https://registry.khronos.org/webgl/sdk/tests/webgl-conformance-tests.html

I might add a link to a WebGL test to Photini's new "failed to load map" page displayed on a map tab. This might help some users track down any WebGL problems.

**Comment by regexgit** [comment]
I completely understand your point of view. Your last answer is very clear and I think you should also add it to the documentation, it would prevent other naggers like me from adding bug reports on the same subject.

**Comment by jim-easterbrook** [comment]
Documentation of next release's map failure handling.
https://photini.readthedocs.io/en/latest/manual/map.html#map-failures
