### ISSUE TITLE
Error reading metadata

### ISSUE THREAD

**Issue by HydrelioxGitHub** [jim-easterbrook/Photini#51]
When I click on some photos I have this error : 

```
22:25:16: ERROR: photini.exiv2: 20131205_155439.jpg(description), Exif.Photo.UserComment: 'ascii' codec can't decode byte 0xf8 in position 1: ordinal not in range(128)
```
I suppose it's because there is maybe a 'ë' character in the metatdata. It's for the word 'Noël' which mean Christmas in French.

**Comment by jim-easterbrook** [comment]
Photini supports accented characters in metadata, with some restrictions. All modern image files should use UTF-8 encoding, which is what Photini writes. Photini attempts to read data using other encodings, but can't always succeed. This is partly due to a limitation in the PyGObject wrapper for libexiv - in Python 3 it decodes all strings with UTF-8, throwing an exception if that fails. Some data can be read as raw bytes and then decoded with other likely encodings (usually Latin-1) but not all.

The error message alerts the user that their metadata might have been corrupted. It tells you which file and which data field ('description'). If you correct any errors and save the file it will be read without errors next time.

If you can send me one of the problem files I can check it isn't using an encoding I haven't encountered before. I like to have a "rogues gallery" of problem files for testing.

**Comment by HydrelioxGitHub** [comment]
Where can you send the file ?

**Comment by jim-easterbrook** [comment]
You could attach it here (which would make it very public) or email it to me jim@jim-easterbrook.me.uk and I'll keep it private.

**Comment by HydrelioxGitHub** [comment]
I sent it to your email address with "Photini issue #51" for subject.

**Comment by jim-easterbrook** [comment]
Thanks - received and I'm already testing it.

**Comment by jim-easterbrook** [comment]
That's interesting. The problem is in the `Exif.Photo.UserComment` value, which was an early attempt by Exif to allow non-ascii characters in metadata. The first 8 bytes are supposed to be the name of the character set used, and in this example they are `ASCII\x00\x00\x00`. The file says it was created by Adobe Photoshop, which I would have expected to do it properly.

**Comment by HydrelioxGitHub** [comment]
I think Photoshop I mentioned only because I pixelate faces. It comes from
an old Samsung smartphone. And has been manipulated using Picasa.

Le mar. 27 oct. 2020 à 11:46, Jim Easterbrook <notifications@github.com> a
écrit :

**Comment by jim-easterbrook** [comment]
That `ZDFI02` sequence is the `Exif.Photo.ImageUniqueID` value, and appears to be a phone camera model number. Maybe Photoshop isn't to blame and just left `Exif.Photo.UserComment` untouched.

**Comment by jim-easterbrook** [comment]
Ah, I would have preferred to have the original image before any modification. It's very likely that Photoshop changed the metadata. (It certainly set `Exif.Image.Software`.)

**Comment by jim-easterbrook** [comment]
See also https://github.com/drewnoakes/metadata-extractor/issues/105
This confirms that it's a Samsung phone standard-breaking misuse of metadata, so I probably won't be able to make any sense of it.

**Comment by jim-easterbrook** [comment]
It gets worse. The binary data they're storing in `Exif.Photo.UserComment` can include JPEG start or stop markers, confusing any reader that scans the file looking for such markers before doing any metadata parsing.
http://sentryytech.blogspot.com/2013/02/fix-corrupted-jpegs-made-by-samsung.html

**Comment by jim-easterbrook** [comment]
I've found some more examples on the web, and the data looks similar. Unless someone out there has reverse engineered this Samsung specific metadata I'm not planning to make any change to Photini. It does the best it can under the circumstances.

**Comment by HydrelioxGitHub** [comment]
I understand and thanks for your time. I think this issue should be closed as it's not related to Photini but related to Samsung.

**Comment by jim-easterbrook** [comment]
Do you have any Samsung software that might make use of this information? At present Photini will wipe the information when a user updates the "description" field, but if it's important then it should be preserved.

**Comment by jim-easterbrook** [comment]
In commit 1e7e707 I've added a warning to the user when `Exif.Photo.UserComment` contains unreadable data (for whatever reason) that will get deleted when Photini saves its metadata.
